Ensure proper error messages end up in stack trace
express-jwt's stack traces don't include error message.
Using the library I was getting error messages like this:

Error
    at /home/mike/projects/cloned/express-jwt/lib/index.js:101:22
    at /home/mike/projects/cloned/express-jwt/node_modules/jsonwebtoken/index.js:54:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Error.captureStackTrace uses the type and the message during the
creation of the stack trace. This commit calls Error.captureStackTrace
after setting name and message so that the stack trace includes the
description like so:

UnauthorizedError: invalid signature
    at /home/mike/projects/cloned/express-jwt/lib/index.js:101:22
    at /home/mike/projects/cloned/express-jwt/node_modules/jsonwebtoken/index.js:54:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)